### PR TITLE
SKYOPS-26453 : Update sling-feature-cpconverter version to 1.1.12 in aemanalyser-maven-plugin

### PR DESCRIPTION
**Pull request by anchela**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] dependency update

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by anchela** [comment]
@bosschaert , @karlpauls , @rombert , i would appreciate if one of you had time to review and merge this PR. thanks a lot.

**Comment by rombert** [comment]
@anchela  - LGTM, but I think you need to sort out the CLA first

**Comment by anchela** [comment]
@anchela , how do i sort that out? i forgot to hit the checkbox. why on earth do i need to do this if i am an adobe employee.

**Comment by rombert** [comment]
Merging until we sort out the CLA thing, thanks for the contribution @anchela

**Pull request merged**
