### PR TITLE
Introduce the aemanalyer-cli command-line tool.

### LINKED ISSUE #81: Make it possible to run the AEM Analyser outside of Maven as a standalone tool
Right now the AEM Analyser is implemented as a Maven Plugin.

However we need to run the Analyser in scenarios where Maven is not present. For this a standalone tool that executes the AEM Analyser is needed.

### PR DESCRIPTION
**Pull request by bosschaert**
For this I have split up the codebase into 3 parts:

* aemanalyser-core: shared code between the tools
* aemanalyser-cli: the commandline tool
* aemanalyser-maven-plugin: the maven plugin as before

The commandline tool currently has a zip-based distro. This can be expanded anywhere on the file system to get the tool with all its dependencies in place. Then it can be run like this:

```
$ java -jar analyser.jar -h
Usage: analyse [-hV] [-a=<analysers>]... [-f=<featureFiles>]...
Execute feature model analysers
  -a, --analyser=<analysers>
                  Analysers to execute
  -f, --features=<featureFiles>
                  Feature files to analyser
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
```

This fixes #81

### CODE REVIEW

**Review by cziegeler — APPROVED** [review]
Lgtm, we eventually need to figure out why we need the class with the method overrides for the CLI to work, but we can do that in another step

**Comment by bosschaert** [comment]
> we eventually need to figure out why we need the class with the method overrides for the CLI to work, but we can do that in another step

Yes, I wasn't 100% sure whether that was the best approach but at least I needed to do _something_ there to make it work for the CLI. We can improve that going forward.

**Comment by kwin** [comment]
A README listing the CLI options would be nice and also https://github.com/adobe/aemanalyser-maven-plugin/blob/main/README.md needs some adjustment.

**Comment by bosschaert** [comment]
@kwin yes you are right. I will provide this shortly.

**Pull request merged**
