### PR TITLE
 SLING-12197 - Fix lacking repoinit statements

### PR DESCRIPTION
**Pull request by niekraaijmakers**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by niekraaijmakers** [comment]
cc @cziegeler @DominikSuess @karlpauls  
ready for review.

**Comment by niekraaijmakers** [comment]
@mtilburgadobe fyi

**Review by DominikSuess — APPROVED** [review]

**Comment by rombert** [comment]
Thanks a lot for taking the time to prepare this @niekraaijmakers ! I have two questions around the fix

- can you please create a GitHub issue in this repo and explain what the fix does?
- does it make sense to always generate the repoinit statements? When AEM users include the maven plugin in their builds, do they get anything out of this? They might, for instance, if we plan to start analysing repoinit statements, but want to make sure that this is a conscious decision

Thanks!

**Comment by stefanseifert** [comment]
great, thanks for the quick fix!

i've provided a small update PR to this which uses different versions of wcm.io handler JARs for testing - because in the latest versions we included a workaround for SLING-12197, and this PR uses older versions without that workaround.
https://github.com/adobe/aemanalyser-maven-plugin/pull/221

**Comment by niekraaijmakers** [comment]
> Thanks a lot for taking the time to prepare this @niekraaijmakers ! I have two questions around the fix
> 
> * can you please create a GitHub issue in this repo and explain what the fix does?
> * does it make sense to always generate the repoinit statements? When AEM users include the maven plugin in their builds, do they get anything out of this? They might, for instance, if we plan to start analysing repoinit statements, but want to make sure that this is a conscious decision
> 
> Thanks!

Il create a github issue. The idea is to keep the local & integrated build aligned as much as possible.

**Pull request merged**
