### PR TITLE
SKYOPS-29433 - switch analyze content package analyzer from WARN to E…

### PR DESCRIPTION
**Pull request by cschneider**
…RROR

## Types of changes

Theoretically breaking as we enforce the checks but no existing builds are affected.
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cschneider** [comment]
@niekraaijmakers please review.

**Review by niekraaijmakers — APPROVED** [review]

**Comment by niekraaijmakers** [comment]
LGTM.

**Comment by cschneider** [comment]
@niekraaijmakers I do not have any rights on this repository. Will you take care of merge and rollout?

**Comment by kwin** [comment]
I would strongly recommend to enable option `allowUndeclaredPrefixInFileName` for validator `jackrabbit-docviewparser` before switching to ERROR (https://jackrabbit.apache.org/filevault/validation.html#Standard_Validators)

**Comment by cschneider** [comment]
@kwin Sounds like a good idea. Unfortunately we currently do not have any way to set parameters to validators. 
So that requires some more work.

**Comment by kwin** [comment]
I opened https://issues.apache.org/jira/browse/JCRVLT-639 to change the default in the upcoming version.

**Comment by cschneider** [comment]
@kwin This is great. So I simply wait and update to the new version before we switch to ERROR level.

**Review by bosschaert — APPROVED** [review]

**Comment by kwin** [comment]
@bosschaert IIUC @cschneider wanted to wait until the fix from https://issues.apache.org/jira/browse/JCRVLT-639 is released.

**Comment by bosschaert** [comment]
Ouch I missed that part of the convertation. I guess it would have been handy to change this PR to draft to make that more clear. I'll revert the merge for now then.

**Pull request merged**
