### PR TITLE
Always update metadata for retrieving latest version

### LINKED ISSUE #138: Maven ITs fail out-of-the-box
### Expected Behaviour

Running `mvn clean install` should be successful.

### Actual Behaviour

Running `mvn clean install` fails due to the Maven plug-in ITs not running properly.

```
[INFO] --- maven-invoker-plugin:3.2.2:verify (integration-test) @ aemanalyser-maven-plugin ---
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  content-package-files-test/pom.xml
[ERROR] *  wknd-test/pom.xml
[INFO] -------------------------------------------------
```

The error that is reported is

```
[ERROR] Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:1.4.0-SNAPSHOT:project-analyse (aem-analyser) on project aemanalyser-maven-plugin-it-content-package-files-test: Failed to resolve version for com.adobe.aem:aemanalyser-maven-plugin:jar:RELEASE -> [Help 1]
```

This is with 
```
$ git describe HEAD
aemanalyser-maven-plugin-1.3.0-9-gde8887f
```

### PR DESCRIPTION
**Pull request by kwin**
This fixes #138

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rombert** [comment]
Isn't the _always_ update policy a bit too eager? Maybe we can force it to _daily_. IIUC, the remote check will happen once every 24 hours, but the warning will always be printed if a remote check discovers an out-of-date artifact.

**Comment by kwin** [comment]
If you don’t update always it really depends on your local repo state. If you only have snapshots in it last updated today you run into the exception you experienced

**Comment by kwin** [comment]
I won't have time for that, this fixes an issue that @rombert and was supposed to be the better fix instead of #140. Just merging #140 without even considering my concern on that feels a bit rude.

**Comment by bosschaert** [comment]
Apologies, I didn't see your comment on the PR, but it was so small and seemed to me like a harmless fix for the problem. We can always revert #140 once this PR is in.

**Review by cziegeler — APPROVED** [review]
Thanks, lgtm

**Pull request merged**
