### PR TITLE
only use stable Jackrabbit releases (fixes #173)

### LINKED ISSUE #173: Usage of unstable Jackrabbit releases
Please do not use unstable Jackrabbit releases; see https://jackrabbit.apache.org/jcr/downloads.html for details.

### PR DESCRIPTION
**Pull request by reschke**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bosschaert** [comment]
We should update the https://github.com/apache/sling-org-apache-sling-feature-cpconverter to these versions first and then pick them up here too. So I'm keeping this PR open until that's done.

**Comment by bosschaert** [comment]
@reschke could you please file the Adobe CLA so that that check doesn't fail?

**Comment by bosschaert** [comment]
I've updated the jackrabbit versions to the ones used by cpconverter 1.1.18, which are slightly different than in this PR, so that these are lined up.

**Comment by reschke** [comment]
> I've updated the jackrabbit versions to the ones used by cpconverter 1.1.18 (https://github.com/adobe/aemanalyser-maven-plugin/commit/df7493f6c217c773b31ccb89c22adcb6e4c8fc93), which are slightly different than in this PR, so that these are lined up.

FWIW, consistency is good, but that shouldn't mean using outdated versions throughout.

**Pull request closed without merging**
