### PR TITLE
Require at least Apache Maven 3.8.1

### PR DESCRIPTION
**Pull request by cziegeler**
With this change we require a more recent Apache Maven for building projects, 3.8.1. which is out since April 2021.

## Description

Update the minimum Apache Maven version as well as the dependencies to the plugins and some other artifacts.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by stefanseifert** [comment]
afaik adobe cloud manager is still running with Maven 3.6.0

**Comment by cziegeler** [comment]
@stefanseifert Thanks, that should be changed as well :)

**Comment by kwin** [comment]
Any ETA when Cloud Manager will be updated to a more recent Maven version (which is not 4.5 years old)?

**Comment by cziegeler** [comment]
Cloud Manager has been updated to Apache Maven 3.8.8 end of 2023

**Pull request merged**
