### PR TITLE
added copying artifact-rules from productAggregates to userResult

### PR DESCRIPTION
**Pull request by michalwedzik**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cziegeler** [comment]
Do we have a bug at the moment (apart from the lenient property)? If I understand it correctly the artifact rules are checked, but against the final feature not the user feature right now.

**Comment by cziegeler** [comment]
@rombert  Thanks, I think there is a bigger problem here. Everything was working "fine" with release 1.4.12 where I get the below output. The next release (strangely 1.5.10) broke it and deprecation checks as well as artifact rules are not applied anymore.
```
[WARNING] Project is configured with outdated aemanalyser plugin version : 1.4.12
[WARNING] Please update to plugin version : 1.5.12
[WARNING] The analyser found the following warnings for author and publish :
[WARNING] [region-deprecated-api] com.adobe.aem.guides:aem-guides-wknd.core:3.0.1-SNAPSHOT: Usage of deprecated package found : com.google.common.collect : The Google Guava Core Libraries are deprecated and will not be part of the AEM SDK after April 2023 Deprecated since 2022-12-01 For removal : 2023-04-01 (com.adobe.aem.guides:aem-guides-wknd.all:3.0.1-SNAPSHOT)
```
Switching to 1.5.10 (or 1.5.12) will remove the last two warnings!

So I have the feeling that reverting the changes that broke it between 1.4.12 and 1.5.10 should solve both issues

**Comment by rombert** [comment]
Ah, interesting. @michalwedzik - would you have time to check exactly which version and which commit broke this? I think you already have a test project for checking the rules.

**Comment by cziegeler** [comment]
I can confirm that the artifact rules work in 1.1.10 of the plugin where they were introduced, I'll now try to find out which version is the first one where it broke

**Comment by cziegeler** [comment]
I created #227 for the reporting of deprecated API

**Comment by cziegeler** [comment]
@michalwedzik This PR fixes the artifact rules (in the same way we handle configuration api checks) https://github.com/adobe/aemanalyser-maven-plugin/pull/229
/cc @rombert

**Comment by rombert** [comment]
@cziegeler  - #229 looks good to me

**Comment by michalwedzik** [comment]
For me also, I've checked locally and it works

**Pull request closed without merging**
